import type {
  AIDetectionEvent,
} from "../../model/ai-monitoring.model";

interface DetectionEventTableProps {
  events: AIDetectionEvent[];
}

function getResultStyle(result: AIDetectionEvent["result"]) {
  const positive =
    result === "Compliant" || result === "Clear";

  return positive
    ? "bg-emerald-50 text-emerald-700"
    : "bg-red-50 text-red-700";
}

export default function DetectionEventTable({
  events,
}: DetectionEventTableProps) {
  return (
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
      <div className="border-b border-slate-100 p-6">
        <h3 className="text-lg font-semibold text-slate-950">
          Recent AI Detection Events
        </h3>

        <p className="mt-1 text-sm text-slate-500">
          Recent metadata generated by the edge AI monitoring
          process.
        </p>
      </div>

      <div className="overflow-x-auto">
        <table className="w-full text-left">
          <thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500">
            <tr>
              <th className="px-6 py-3 font-semibold">
                Time
              </th>

              <th className="px-6 py-3 font-semibold">
                Detection
              </th>

              <th className="px-6 py-3 font-semibold">
                Category
              </th>

              <th className="px-6 py-3 font-semibold">
                Confidence
              </th>

              <th className="px-6 py-3 font-semibold">
                Result
              </th>
            </tr>
          </thead>

          <tbody className="divide-y divide-slate-100">
            {events.map((event) => (
              <tr
                key={event.id}
                className="text-sm text-slate-700"
              >
                <td className="whitespace-nowrap px-6 py-4">
                  {event.timestamp}
                </td>

                <td className="px-6 py-4 font-medium text-slate-900">
                  {event.detection}
                </td>

                <td className="px-6 py-4">
                  {event.category}
                </td>

                <td className="px-6 py-4">
                  {event.confidence}%
                </td>

                <td className="px-6 py-4">
                  <span
                    className={`rounded-full px-2.5 py-1 text-xs font-semibold ${getResultStyle(
                      event.result
                    )}`}
                  >
                    {event.result}
                  </span>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </section>
  );
}