import {
  Blocks,
  CircleCheckBig,
  Clock3,
  ShieldCheck,
  LockKeyhole,
} from "lucide-react";

import type {
  AuditTrailData,
} from "../model/audit.model";

import AuditSummaryCard from "./components/AuditSummaryCard";
import AuditRecordTable from "./components/AuditRecordTable";

interface AuditTrailViewProps {
  data: AuditTrailData;
}

export default function AuditTrailView({
  data,
}: AuditTrailViewProps) {
  return (
    <div className="mx-auto max-w-7xl">
      <div className="mb-8">
        <p className="text-sm font-medium text-emerald-600">
          Digital Trust
        </p>

        <h2 className="mt-1 text-2xl font-bold tracking-tight text-slate-950 sm:text-3xl">
          Audit Trail
        </h2>

        <p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">
          Review important hygiene events selected for
          blockchain-supported tamper-aware audit logging.
        </p>
      </div>

      <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <AuditSummaryCard
          label="Total Records"
          value={data.summary.totalRecords}
          icon={Blocks}
          description="Important hygiene events prepared for audit logging."
        />

        <AuditSummaryCard
          label="Verified"
          value={data.summary.verifiedRecords}
          icon={CircleCheckBig}
          description="Records successfully confirmed by the audit layer."
        />

        <AuditSummaryCard
          label="Pending"
          value={data.summary.pendingRecords}
          icon={Clock3}
          description="Records awaiting blockchain confirmation."
        />

        <AuditSummaryCard
          label="Failed"
          value={data.summary.failedRecords}
          icon={ShieldCheck}
          description="Records that could not be confirmed successfully."
        />
      </section>

      <section className="mt-8 rounded-2xl border border-violet-200 bg-violet-50/60 p-6">
        <div className="flex items-start gap-4">
          <div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-white">
            <LockKeyhole className="h-5 w-5 text-violet-700" />
          </div>

          <div>
            <h3 className="font-semibold text-violet-950">
              Tamper-Aware Audit Layer
            </h3>

            <p className="mt-2 max-w-4xl text-sm leading-6 text-violet-800">
              The blockchain layer does not perform hygiene
              detection. It is used to preserve the integrity of
              selected important hygiene events after they have
              been generated by the AI, IoT and scoring layers.
            </p>

            <div className="mt-4 flex flex-wrap gap-3">
              <span className="rounded-lg bg-white px-3 py-2 text-xs font-medium text-violet-800">
                Network: {data.networkName}
              </span>

              <span className="rounded-lg bg-white px-3 py-2 text-xs font-medium text-violet-800">
                Platform: {data.ledgerType}
              </span>
            </div>
          </div>
        </div>
      </section>

      <div className="mt-8">
        <AuditRecordTable
          records={data.records}
        />
      </div>
    </div>
  );
}